/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;


/**
 *
 * @author Meshith
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbBranch = new javax.swing.JComboBox<>();
        btnNext = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1070, 590));
        setUndecorated(true);
        setOpacity(0.99F);
        setPreferredSize(new java.awt.Dimension(1070, 590));
        setResizable(false);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20)
        );
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Body.setBackground(new java.awt.Color(0, 0, 0));
        Body.setPreferredSize(new java.awt.Dimension(1070, 590));
        Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/logo (1) (1).png"))); // NOI18N
        Body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Branch");
        Body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 220, 87, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        Body.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 152, 66, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        Body.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 192, 380, -1));

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Area", "Kandy", "Colombo", "Galle", "Jaffna" }));
        Body.add(cmbBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 267, 380, -1));

        btnNext.setBackground(new java.awt.Color(50, 50, 50));
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setLabel("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        Body.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 168, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/backgroundlogin.jpg"))); // NOI18N
        Body.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -870, 630, -1));

        getContentPane().add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 610, 560));

        Image.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Image.setForeground(new java.awt.Color(255, 255, 255));
        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/loginteeth.jpg"))); // NOI18N
        Image.setText("image");
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 730, 600));

        Header.setBackground(new java.awt.Color(50, 50, 50));
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Header.setPreferredSize(new java.awt.Dimension(1080, 40));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/crossw.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(1030, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 40));

        getAccessibleContext().setAccessibleName("Login");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     int xx,xy;
    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        // TODO add your handling code here:
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/crossr.png")));
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        // TODO add your handling code here:
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/crossw.png")));
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
         xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    
    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_HeaderMouseDragged

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        String branch = cmbBranch.getSelectedItem().toString();
        String name = txtName.getText();
       if(txtName.getText().equals("")||branch.equals("Select Area")){
           JOptionPane.showMessageDialog(this, "Please Enter All the Data!");
       }else{
            this.dispose();
            new Home(name,branch).setVisible(true);
       }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Image;
    private java.awt.Button btnNext;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
